# Filenaam: azure-pipelines.yml
# Functie: Voorbeeld van een yaml Build en Publish script tbv Azure DevOps,
#          waarmee een ASP .NET voorbeeld project kan worden ge-build en ge-deployed.
#
#          Het voorbeeld is afkomst van 
#          Microsoft learn
#          https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
#            
# Dit script laat ook zien hoe dit script gebruik maakt van template yaml scripts
# waarmee standaard yaml functionaliteit tijdens het build of deploy proces kan worden
# gestandardiseerd.
#
# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# 

trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()